config/routes.rb
StoryBook::Application.routes.draw do
  resources :paragraphs

  resources :stories
  
  
 

  resources :books

  get "books/index"

  get "books/show"

  get "books/edit"

  get "book/index"

  get "book/show"

  get "book/edit"
  get "sessions/new"
  
  root :to => 'books#index'
  
  resources :sessions 
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
 

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :stories
  
  validates_presence_of :title
  validates_presence_of :description
  
  cattr_reader :per_page
  @@per_page = 10
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  before_filter :login_required
  def index
    @books = Book.paginate :page => params[:page], :order => 'created_at DESC'

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :ok }
    end
  end
  
  private
 
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p><label for="title">Title:</label><br/>
<%= f.text_field :title %></p>


<p><label for="description">Description</label><br/>
<%= f.text_area :description, :rows => 2, :cols => 80 %></p>


<br/><hr>
<% unless @book.id.blank? %>
  <%= link_to "add new story", new_story_path(:book_id => @book.id) %>
<% end %>
<table>
  <% @book.stories.each do |story| %>

    <tr>
      <td>
        <%= story.title %>
      </td>
      <td>
        <%= link_to "Edit ", edit_story_path(:book_id=> @book.id, :story_id => story.id) %>
        |
        <%= link_to "Preview ", story_path(story.id) %>
      </td>
    </tr>
  <% end %>
</table>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book by me</h1>
<%= render 'form' %>


<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path%>

app/views/books/index.html.erb
<div id="books">

  <table>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Actions</th>
      
    </tr>
  
  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td style="padding-left: 20px;"><%= book.description.html_safe[0..50] %></td>
      <td><%= link_to 'Show', book %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Destroy', book, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
  </table>
  
  <br />
  
  <%= link_to 'Create a New book', new_book_path %>
  
  <%= will_paginate @books %>
  
</div>

app/views/books/new.html.erb
<h1>New book</h1>


<%= render 'form' %>


<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<table>
  <tr><td><%= @book.title%></td></tr>
  <tr><td><%= @book.description.html_safe%></td></tr>
  <% @book.stories.each do |story| %>
    <hr><h1><%= story.title %><h1>
    <h2><%= story.description.html_safe %> </h2>
    
    <% story.paragraphs.each do |paragraph| %>
      <%= paragraph.body_text.html_safe %>
    <% end %>
  <% end %>
</table>
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>