config/routes.rb
StoryBook::Application.routes.draw do
  resources :paragraphs

  resources :stories
  
  
 

  resources :books

  get "books/index"

  get "books/show"

  get "books/edit"

  get "book/index"

  get "book/show"

  get "book/edit"
  get "sessions/new"
  
  root :to => 'books#index'
  
  resources :sessions 
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
 

end

app/models/story.rb
class Story < ActiveRecord::Base
    belongs_to :book
  has_many :paragraphs
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :login_required
  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stories }
    end
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/new
  # GET /stories/new.json
  def new
    @story = Story.new
    @book = Book.find(params[:book_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:story_id])
    @book = Book.find(params[:book_id])
  end

  # POST /stories
  # POST /stories.json
  def create
    @book = Book.find(params[:story][:book_id])
    @story = @book.stories.create(params[:story])

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render json: @story, status: :created, location: @story }
      else
        format.html { render action: "new" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    @story = Story.find(params[:id])

    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to stories_url }
      format.json { head :ok }
    end
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p><label for="title">Title:</label><br/>
<%= f.text_field :title %></p>


<p><label for="description">Description</label><br/>
<%= f.text_area :description, :rows => 2, :cols => 80 %></p>
<%= f.hidden_field :book_id, :value => @book.id %>


<hr>
<% unless @story.id.blank? %>
  <%= link_to "add new paragraph", new_paragraph_path(:story_id => @story.id) %>
<% end %>
    
<table>

  <% @story.paragraphs.each do |paragraph| %>

    <tr>
      <td>
        <%= paragraph.title %>
      </td>
      <td>
        <%= link_to "Edit " + paragraph.title, edit_paragraph_path(:story_id=> @story.id, :paragraph_id => paragraph.id) %>
      </td>
    </tr>

  <% end %>
</table>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', edit_book_path(@book) %>

app/views/stories/index.html.erb
<h1>Listing stories</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stories.each do |story| %>
  <tr>
    <td><%= link_to 'Show', story %></td>
    <td><%= link_to 'Edit', edit_story_path(story) %></td>
    <td><%= link_to 'Destroy', story, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @story.title %></hi>
<hr>
<div id="paragraph_content">
  <% for paragraph in @story.paragraphs %>
    <p><%= paragraph.body_text.html_safe %></p>
  <% end %>
</div>


<%= link_to 'Edit', edit_story_path(:story_id => @story.id, :book_id => @story.book.id) %> |
<%= link_to 'Back', edit_book_path(@story.book)  %>