config/routes.rb
StoryBook::Application.routes.draw do
  resources :paragraphs

  resources :stories
  
  
 

  resources :books

  get "books/index"

  get "books/show"

  get "books/edit"

  get "book/index"

  get "book/show"

  get "book/edit"
  get "sessions/new"
  
  root :to => 'books#index'
  
  resources :sessions 
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
 

end

app/models/paragraph.rb
class Paragraph < ActiveRecord::Base
    belongs_to :story
end

app/controllers/paragraphs_controller.rb
class ParagraphsController < ApplicationController
  before_filter :login_required
  # GET /paragraphs
  # GET /paragraphs.json
  def index
    @paragraphs = Paragraph.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @paragraphs }
    end
  end

  # GET /paragraphs/1
  # GET /paragraphs/1.json
  def show
    @paragraph = Paragraph.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @paragraph }
    end
  end

  # GET /paragraphs/new
  # GET /paragraphs/new.json
  def new
    @paragraph = Paragraph.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @paragraph }
    end
  end

  # GET /paragraphs/1/edit
  def edit
    @paragraph = Paragraph.find(params[:paragraph_id])
    @story = Story.find(params[:story_id])
  end

  # POST /paragraphs
  # POST /paragraphs.json
  def create
    @paragraph = Paragraph.new(params[:paragraph])

    respond_to do |format|
      if @paragraph.save
        format.html { redirect_to @paragraph, notice: 'Paragraph was successfully created.' }
        format.json { render json: @paragraph, status: :created, location: @paragraph }
      else
        format.html { render action: "new" }
        format.json { render json: @paragraph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /paragraphs/1
  # PUT /paragraphs/1.json
  def update
    @paragraph = Paragraph.find(params[:id])

    respond_to do |format|
      if @paragraph.update_attributes(params[:paragraph])
        format.html { redirect_to @paragraph, notice: 'Paragraph was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @paragraph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paragraphs/1
  # DELETE /paragraphs/1.json
  def destroy
    @paragraph = Paragraph.find(params[:id])
    @paragraph.destroy

    respond_to do |format|
      format.html { redirect_to paragraphs_url }
      format.json { head :ok }
    end
  end
end

app/helpers/paragraphs_helper.rb
module ParagraphsHelper
end

app/views/paragraphs/_form.html.erb
<%= form_for(@paragraph) do |f| %>
  <% if @paragraph.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paragraph.errors.count, "error") %> prohibited this paragraph from being saved:</h2>

      <ul>
      <% @paragraph.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p><label for="title">Title:</label><br/>
  <%= f.text_field :title %></p>

  <p><label for="body_text">Paragraph</label><br/>
  <%= f.text_area :body_text, :rows => 20, :cols => 80, :class => "mceEditor" %></p>
  <%= f.hidden_field :story_id, :value => @story.id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paragraphs/edit.html.erb
<h1>Editing paragraph</h1>

<%= render 'form' %>

<%= link_to 'Show', @paragraph %> |
<%= link_to 'Back', "/stories/#{@story.id}/edit?book_id=#{@story.book.id}&story_id=#{@story.id}" %>

app/views/paragraphs/index.html.erb
<h1>Listing paragraphs</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @paragraphs.each do |paragraph| %>
  <tr>
    <td><%= link_to 'Show', paragraph %></td>
    <td><%= link_to 'Edit', edit_paragraph_path(paragraph) %></td>
    <td><%= link_to 'Destroy', paragraph, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Paragraph', new_paragraph_path %>

app/views/paragraphs/new.html.erb
<h1>New paragraph</h1>

<%= render 'form' %>

<%= link_to 'Back', paragraphs_path %>

app/views/paragraphs/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_paragraph_path(@paragraph) %> |
<%= link_to 'Back', paragraphs_path %>